[package]
name = "core"
version = "0.1.0"
edition = "2024"
resolver = "2"

[lib]
name = "_core"
crate-type = ["cdylib", "lib"]
path = "src-rust/lib.rs"

[dependencies]
ndarray = { version = "0.17.2", features = ["rayon"] }
numpy = "0.29"
pyo3 = "0.29"

[dev-dependencies]
ndarray = { version = "0.17.2", features = ["rayon", "approx"] }
approx = "0.5.1"
criterion = { version = "0.8.2", features = ["html_reports"] }
proptest = "1.11.0"

[[bench]]
name = "intensity_benchmarks"
harness = false
