"""Tests for Konno-Ohmachi smoothing and the matrix store behind it.

These exercise the module through its public surface -- `smooth`,
`smoothing_matrix`, `MatrixStore` and the two runtime knobs -- so that how the
store tiers, keys, evicts or spills its matrices stays free to change.
"""

import multiprocessing
from collections.abc import Iterator
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import numpy.typing as npt
import pytest

from IM import konno_ohmachi

REFERENCE_MATRIX = Path(__file__).parent / "resources" / "konno_reference_n65_b40.npy"
REFERENCE_DIRECT = (
    Path(__file__).parent / "resources" / "konno_reference_direct_n65_b40.npz"
)


def obspy_smoothing_matrix(n_bins: int, bandwidth: float) -> npt.NDArray[np.float64]:
    """Transcription of obspy's `calculate_smoothing_matrix(..., normalize=True)`.

    obspy is no longer a dependency, so this stands in as an independent oracle
    for sizes and bandwidths the committed reference matrix does not cover. It
    is checked against that reference by `test_oracle_matches_reference`, so a
    transcription slip cannot quietly pass as agreement.

    Derived from `obspy.signal.konnoohmachismoothing` (LGPL-3.0).
    """
    freqs = np.fft.rfftfreq((n_bins - 1) * 2)
    matrix = np.empty((n_bins, n_bins), dtype=np.float64)
    for centre, frequency in enumerate(freqs):
        if frequency == 0:
            matrix[centre] = (freqs == 0.0).astype(np.float64)
            continue
        with np.errstate(divide="ignore", invalid="ignore"):
            x = bandwidth * np.log10(freqs / frequency)
            window = (np.sin(x) / x) ** 4
        window[freqs == frequency] = 1.0
        window[freqs == 0.0] = 0.0
        matrix[centre] = window / window.sum()
    return matrix


def _store_size(_: int) -> int:
    """Report how many matrices the default store holds.

    Module level, so `fork` children can import and call it.
    """
    return len(konno_ohmachi.MATRICES)


@pytest.fixture(autouse=True)
def scratch(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Iterator[Path]:
    """Give each test an empty matrix store spilling to its own directory.

    Both settings are pinned through `monkeypatch`, so a test that changes them
    -- including via `set_scratch_directory` / `set_memory_budget` -- cannot leak
    them into the next one, even if it fails partway. Spilled matrices are
    unlinked as they are created, so the directory being empty afterwards is a
    file-wide invariant rather than a per-test assertion.
    """
    scratch_directory = tmp_path / "scratch"
    scratch_directory.mkdir()
    monkeypatch.setattr(konno_ohmachi.MATRICES, "scratch_directory", scratch_directory)
    monkeypatch.setattr(
        konno_ohmachi.MATRICES, "memory_budget", konno_ohmachi.DEFAULT_MEMORY_BUDGET
    )
    konno_ohmachi.clear_matrix_cache()
    yield scratch_directory
    konno_ohmachi.clear_matrix_cache()
    assert list(scratch_directory.iterdir()) == []


@pytest.fixture(scope="module")
def reference_matrix() -> npt.NDArray[np.float64]:
    """The committed obspy-generated matrix for 65 bins at bandwidth 40."""
    matrix = np.load(REFERENCE_MATRIX)
    matrix.flags.writeable = False
    return matrix


@pytest.fixture(scope="module")
def reference_direct() -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
    """Spectra and their smoothing by obspy's own direct (non-matrix) path."""
    with np.load(REFERENCE_DIRECT) as data:
        spectra, smoothed = data["spectra"], data["smoothed"]
    spectra.flags.writeable = False
    smoothed.flags.writeable = False
    return spectra, smoothed


@pytest.fixture
def spectra() -> npt.NDArray[np.float64]:
    """A positive, smoothly decaying spectrum stack of shape `(2, 3, 65)`."""
    rng = np.random.default_rng(0)
    decay = np.exp(-np.linspace(0, 6, 65))
    return (np.abs(rng.standard_normal((2, 3, 65))) + 0.1) * decay


def test_matrix_matches_obspy_reference(
    reference_matrix: npt.NDArray[np.float64],
) -> None:
    """The kernel reproduces a matrix generated by obspy itself."""
    np.testing.assert_allclose(
        konno_ohmachi.smoothing_matrix(65, 40.0),
        reference_matrix,
        rtol=1e-5,
        atol=1e-12,
    )


def test_oracle_matches_reference(reference_matrix: npt.NDArray[np.float64]) -> None:
    """The vendored oracle agrees with the obspy-generated reference."""
    np.testing.assert_allclose(
        obspy_smoothing_matrix(65, 40.0), reference_matrix, rtol=1e-4, atol=1e-12
    )


@pytest.mark.parametrize("n_bins", [17, 65, 129])
@pytest.mark.parametrize("bandwidth", [20.0, 40.0, 60.5])
def test_matrix_matches_oracle(n_bins: int, bandwidth: float) -> None:
    """The kernel agrees with the oracle across sizes and bandwidths."""
    np.testing.assert_allclose(
        konno_ohmachi.smoothing_matrix(n_bins, bandwidth),
        obspy_smoothing_matrix(n_bins, bandwidth),
        rtol=1e-4,
        atol=1e-12,
    )


def test_matrix_is_row_major_float32() -> None:
    """`smoothing_matrix` returns the row-major float32 array it documents."""
    matrix = konno_ohmachi.smoothing_matrix(65, 40.0)
    assert matrix.dtype == np.float32
    assert matrix.flags["C_CONTIGUOUS"]


def test_smooth_preserves_shape_and_dtype(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Smoothing is elementwise in the leading axes and returns float64."""
    smoothed = konno_ohmachi.smooth(spectra)
    assert smoothed.shape == spectra.shape
    assert smoothed.dtype == np.float64


def test_smooth_matches_reference_product(
    spectra: npt.NDArray[np.float64], reference_matrix: npt.NDArray[np.float64]
) -> None:
    """Each output bin is a weighted average over the whole spectrum.

    Pinned at the bandwidth the reference was generated with, so the obspy
    anchor survives a change of `DEFAULT_BANDWIDTH`.
    """
    reference = (spectra.reshape(-1, 65) @ reference_matrix.T).reshape(spectra.shape)
    # Single precision accumulation over 65 positive weights; ~1e-6 relative.
    assert konno_ohmachi.smooth(spectra, bandwidth=40.0) == pytest.approx(
        reference, rel=1e-5
    )


@pytest.mark.parametrize(
    ("memory_budget", "block_bytes"),
    [
        (konno_ohmachi.DEFAULT_MEMORY_BUDGET, konno_ohmachi.KONNO_BLOCK_BYTES),
        (0, konno_ohmachi.KONNO_BLOCK_BYTES),
        (0, 1),
    ],
    ids=["in-memory", "spilled", "spilled-one-row-blocks"],
)
def test_smooth_matches_obspy_direct_path(
    reference_direct: tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]],
    memory_budget: int,
    block_bytes: int,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Smoothing reproduces obspy's direct (non-matrix) smoothing, however served.

    This is the convention pin. obspy's matrix path contracts over the other
    index and disagrees with its direct path by up to 30%, so agreeing with the
    matrix product alone would not distinguish the two.

    Repeated across the tiers, and at one row per block so that every block
    boundary is exercised, because where the matrix lives and how it is chunked
    must not change the numbers. A budget of zero also means zero, rather than
    falling back to the default.
    """
    spectra, smoothed = reference_direct
    konno_ohmachi.set_memory_budget(memory_budget)
    monkeypatch.setattr(konno_ohmachi, "KONNO_BLOCK_BYTES", block_bytes)

    assert konno_ohmachi.smooth(spectra, bandwidth=40.0) == pytest.approx(
        smoothed, rel=1e-5
    )


@pytest.mark.parametrize(
    "unusable", ["not-a-directory", "no-free-space", "build-fails"]
)
def test_smooth_falls_back_when_the_matrix_fits_nowhere(
    reference_direct: tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]],
    unusable: str,
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """With no memory budget and no usable scratch, smoothing still works.

    Every way the scratch directory can refuse a matrix is a warning and a
    slower answer, never an exception and never a partial file left behind --
    the `scratch` fixture asserts the latter for us.
    """
    spectra, smoothed = reference_direct
    konno_ohmachi.set_memory_budget(0)

    if unusable == "not-a-directory":
        blocker = tmp_path / "blocker"
        blocker.write_text("not a directory")
        monkeypatch.setattr(
            konno_ohmachi.MATRICES, "scratch_directory", blocker / "under"
        )
    elif unusable == "no-free-space":
        monkeypatch.setattr(
            konno_ohmachi.shutil, "disk_usage", lambda _: SimpleNamespace(free=0)
        )
    else:

        def fail(*_args: object, **_kwargs: object) -> None:
            raise OSError("no space left on device")

        monkeypatch.setattr(konno_ohmachi._core, "_konno_ohmachi_matrix_rows", fail)

    with pytest.warns(RuntimeWarning, match="matrix-free"):
        matrix_free = konno_ohmachi.smooth(spectra, bandwidth=40.0)

    assert matrix_free == pytest.approx(smoothed, rel=1e-5)


def test_flat_spectrum_is_returned_unchanged() -> None:
    """The weights behind every output bin sum to one.

    Contracting over the centre index instead would attenuate the band edges by
    up to 25%, which is the failure this guards against.
    """
    flat = np.ones((1, 65))
    assert konno_ohmachi.smooth(flat) == pytest.approx(flat, rel=1e-6)


def test_matrix_is_built_once_per_size_and_bandwidth(
    spectra: npt.NDArray[np.float64], monkeypatch: pytest.MonkeyPatch
) -> None:
    """A repeat call reuses the matrix, and bandwidth is part of its identity.

    A store that ignored bandwidth would serve the first matrix to the second
    call and build only once.
    """
    original = konno_ohmachi.smoothing_matrix
    built: list[tuple[int, float]] = []

    def counting(n_bins: int, bandwidth: float) -> npt.NDArray[np.float32]:
        built.append((n_bins, bandwidth))
        return original(n_bins, bandwidth)

    monkeypatch.setattr(konno_ohmachi, "smoothing_matrix", counting)

    wide = konno_ohmachi.smooth(spectra, bandwidth=10.0)
    again = konno_ohmachi.smooth(spectra, bandwidth=10.0)
    narrow = konno_ohmachi.smooth(spectra, bandwidth=80.0)

    assert built == [(65, 10.0), (65, 80.0)]
    assert again == pytest.approx(wide, rel=1e-12)
    assert not np.allclose(wide, narrow)


def test_clear_matrix_cache_empties_the_store(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Clearing genuinely releases the matrices the store was holding."""
    konno_ohmachi.smooth(spectra)
    assert len(konno_ohmachi.MATRICES) == 1

    konno_ohmachi.clear_matrix_cache()
    assert len(konno_ohmachi.MATRICES) == 0


def test_memory_budget_bounds_what_the_store_holds() -> None:
    """The budget caps the total held, not the size of any one matrix.

    Three matrices that each fit the budget on their own are held two at a
    time, because what the budget bounds is their sum.
    """
    one = konno_ohmachi.smoothing_matrix(65, 40.0).nbytes
    store = konno_ohmachi.MatrixStore(memory_budget=2 * one + 1)

    for bandwidth in (10.0, 20.0, 30.0):
        assert store.get(65, bandwidth) is not None

    assert len(store) == 2


def test_set_scratch_directory_chooses_where_matrices_spill(
    spectra: npt.NDArray[np.float64], tmp_path: Path
) -> None:
    """`set_scratch_directory` is the runtime knob `calculate_ims` drives.

    The environment is only read when a store is built, and `MATRICES` is built
    at import, so setting the variable afterwards would not reach it.
    """
    chosen = tmp_path / "chosen"
    konno_ohmachi.set_scratch_directory(chosen)
    konno_ohmachi.set_memory_budget(0)

    konno_ohmachi.smooth(spectra)

    # Only spilling creates the directory, so its existence is the evidence.
    assert chosen.is_dir()
    # The scratch file is unlinked as it is created, so nothing is left behind.
    assert list(chosen.iterdir()) == []


def test_concurrent_smoothing_is_consistent(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Several threads racing on one size all get the same answer.

    A thread that loses the race to build must take the winner's matrix rather
    than a half-built one.
    """
    with ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(lambda _: konno_ohmachi.smooth(spectra), range(8)))

    for result in results[1:]:
        assert result == pytest.approx(results[0], rel=1e-12)


def test_warm_builds_ahead_of_use(
    spectra: npt.NDArray[np.float64], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Warming builds up front so that later smoothing is a hit, not a rebuild."""
    konno_ohmachi.MATRICES.warm([65, 129])
    assert len(konno_ohmachi.MATRICES) == 2

    def explode(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("a warmed matrix was rebuilt instead of reused")

    monkeypatch.setattr(konno_ohmachi, "smoothing_matrix", explode)
    konno_ohmachi.smooth(spectra)
    konno_ohmachi.MATRICES.warm(65)

    assert len(konno_ohmachi.MATRICES) == 2


@pytest.mark.skipif(
    "fork" not in multiprocessing.get_all_start_methods(),
    reason="fork is unavailable on this platform",
)
def test_forked_children_inherit_a_warmed_store() -> None:
    """A child forked after warming reuses the parent's matrix rather than rebuilding.

    This is the whole reason `warm` exists: a pool forked from a cold parent
    gives every worker its own private copy of every matrix.
    """
    konno_ohmachi.MATRICES.warm(65)

    context = multiprocessing.get_context("fork")
    with context.Pool(2) as pool:
        assert pool.map(_store_size, range(2)) == [1, 1]


def test_caller_can_keep_its_own_store(spectra: npt.NDArray[np.float64]) -> None:
    """A caller can keep its own store rather than sharing the module-level one."""
    store = konno_ohmachi.MatrixStore()

    konno_ohmachi.smooth(spectra, store=store)

    assert len(store) == 1
    assert len(konno_ohmachi.MATRICES) == 0


def test_bins_for_samples_matches_the_fas_padding() -> None:
    """The bin count `warm` takes is the one FAS will actually ask for."""
    for n_samples, expected in ((7144, 4097), (9271, 8193), (21953, 16385)):
        assert konno_ohmachi.bins_for_samples(n_samples) == expected
