"""Tests for Konno-Ohmachi smoothing and the matrix tiers behind it."""

import shutil
from collections.abc import Iterator
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import numpy as np
import numpy.typing as npt
import pytest

from IM import konno_ohmachi

REFERENCE_MATRIX = Path(__file__).parent / "resources" / "konno_reference_n65_b40.npy"


def obspy_smoothing_matrix(n_bins: int, bandwidth: float) -> npt.NDArray[np.float64]:
    """Transcription of obspy's `calculate_smoothing_matrix(..., normalize=True)`.

    obspy is no longer a dependency, so this stands in as an independent oracle
    for sizes and bandwidths the committed reference matrix does not cover. It
    is checked against that reference by `test_oracle_matches_reference`, so a
    transcription slip cannot quietly pass as agreement.

    Derived from `obspy.signal.konnoohmachismoothing` (LGPL-3.0).
    """
    freqs = np.fft.rfftfreq((n_bins - 1) * 2)
    matrix = np.empty((n_bins, n_bins), dtype=np.float64)
    for centre, frequency in enumerate(freqs):
        if frequency == 0:
            matrix[centre] = (freqs == 0.0).astype(np.float64)
            continue
        with np.errstate(divide="ignore", invalid="ignore"):
            x = bandwidth * np.log10(freqs / frequency)
            window = (np.sin(x) / x) ** 4
        window[freqs == frequency] = 1.0
        window[freqs == 0.0] = 0.0
        matrix[centre] = window / window.sum()
    return matrix


@pytest.fixture(autouse=True)
def isolated_matrices(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> Iterator[None]:
    """Give each test its own scratch directory and an empty matrix store."""
    monkeypatch.setenv(konno_ohmachi.SCRATCH_DIRECTORY_VARIABLE, str(tmp_path))
    konno_ohmachi.clear_matrix_cache()
    yield
    konno_ohmachi.clear_matrix_cache()


@pytest.fixture
def spectra() -> npt.NDArray[np.float64]:
    """A positive, smoothly decaying spectrum stack of shape `(2, 3, 65)`."""
    rng = np.random.default_rng(0)
    decay = np.exp(-np.linspace(0, 6, 65))
    return (np.abs(rng.standard_normal((2, 3, 65))) + 0.1) * decay


def test_matrix_matches_obspy_reference() -> None:
    """The kernel reproduces a matrix generated by obspy itself."""
    reference = np.load(REFERENCE_MATRIX)
    assert konno_ohmachi.smoothing_matrix(65, 40.0) == pytest.approx(
        reference, rel=1e-5, abs=1e-12
    )


def test_oracle_matches_reference() -> None:
    """The vendored oracle agrees with the obspy-generated reference."""
    reference = np.load(REFERENCE_MATRIX)
    assert obspy_smoothing_matrix(65, 40.0) == pytest.approx(
        reference, rel=1e-4, abs=1e-12
    )


@pytest.mark.parametrize("n_bins", [17, 65, 129])
@pytest.mark.parametrize("bandwidth", [20.0, 40.0, 60.5])
def test_matrix_matches_oracle(n_bins: int, bandwidth: float) -> None:
    """The kernel agrees with the oracle across sizes and bandwidths."""
    assert konno_ohmachi.smoothing_matrix(n_bins, bandwidth) == pytest.approx(
        obspy_smoothing_matrix(n_bins, bandwidth), rel=1e-4, abs=1e-12
    )


def test_rows_sum_to_one() -> None:
    """Normalisation runs over the evaluation index, so rows sum to one."""
    matrix = konno_ohmachi.smoothing_matrix(129, 40.0)
    assert matrix.sum(axis=1) == pytest.approx(np.ones(129), rel=1e-6)


def test_matrix_is_row_major_float32() -> None:
    """Row blocks of a C-ordered matrix are contiguous, which the tiers rely on."""
    matrix = konno_ohmachi.smoothing_matrix(65, 40.0)
    assert matrix.dtype == np.float32
    assert matrix.flags["C_CONTIGUOUS"]


def test_smooth_preserves_shape_and_dtype(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Smoothing is elementwise in the leading axes and returns float64."""
    smoothed = konno_ohmachi.smooth(spectra)
    assert smoothed.shape == spectra.shape
    assert smoothed.dtype == np.float64


def test_smooth_matches_reference_product(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Smoothing is a product with the obspy matrix, contracted over the centre."""
    reference = (spectra.reshape(-1, 65) @ np.load(REFERENCE_MATRIX)).reshape(
        spectra.shape
    )
    # Single precision accumulation over 65 positive weights; ~1e-6 relative.
    assert konno_ohmachi.smooth(spectra) == pytest.approx(reference, rel=1e-5)


def test_bandwidth_changes_the_result(spectra: npt.NDArray[np.float64]) -> None:
    """Bandwidth is part of the matrix identity, not an ignored argument."""
    wide = konno_ohmachi.smooth(spectra, bandwidth=10.0)
    narrow = konno_ohmachi.smooth(spectra, bandwidth=80.0)
    assert not np.allclose(wide, narrow)


def test_in_memory_tier_writes_nothing(
    spectra: npt.NDArray[np.float64], tmp_path: Path
) -> None:
    """A matrix inside the memory budget never touches the filesystem."""
    konno_ohmachi.smooth(spectra)
    assert list(tmp_path.iterdir()) == []


def test_spilled_tier_leaves_no_file(
    spectra: npt.NDArray[np.float64],
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A spilled matrix is unlinked while still mapped, so nothing is left behind."""
    monkeypatch.setenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, "1")
    spilled = konno_ohmachi.smooth(spectra)

    assert list(tmp_path.iterdir()) == []
    assert isinstance(
        konno_ohmachi._matrix(65, konno_ohmachi.DEFAULT_BANDWIDTH), np.memmap
    )
    # Still usable after the unlink, and identical to the in-memory tier.
    konno_ohmachi.clear_matrix_cache()
    monkeypatch.delenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE)
    assert spilled == pytest.approx(konno_ohmachi.smooth(spectra), rel=1e-12)


def test_matrix_free_tier_when_nothing_fits(
    spectra: npt.NDArray[np.float64], monkeypatch: pytest.MonkeyPatch
) -> None:
    """With no memory budget and no scratch, smoothing still works, with a warning."""
    monkeypatch.setenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, "1")
    monkeypatch.setattr(konno_ohmachi, "_spilled_matrix", lambda *_: None)

    with pytest.warns(RuntimeWarning, match="matrix-free"):
        matrix_free = konno_ohmachi.smooth(spectra)

    konno_ohmachi.clear_matrix_cache()
    monkeypatch.delenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE)
    assert matrix_free == pytest.approx(konno_ohmachi.smooth(spectra), rel=1e-5)


def test_spill_declines_when_scratch_is_unusable(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """An unwritable or absent scratch directory falls through rather than raising."""
    monkeypatch.setenv(
        konno_ohmachi.SCRATCH_DIRECTORY_VARIABLE, str(tmp_path / "file" / "under")
    )
    (tmp_path / "file").write_text("not a directory")
    assert konno_ohmachi._spilled_matrix(65, 40.0) is None


def test_spill_declines_when_disk_is_full(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    """A matrix larger than the free space is declined before anything is written."""
    full = shutil._ntuple_diskusage(total=0, used=0, free=0)
    monkeypatch.setattr(konno_ohmachi.shutil, "disk_usage", lambda _: full)
    assert konno_ohmachi._spilled_matrix(65, 40.0) is None
    assert list(tmp_path.iterdir()) == []


def test_matrix_is_reused_within_a_process(spectra: npt.NDArray[np.float64]) -> None:
    """The second call must not rebuild: the builder is made to fail if it does."""
    first = konno_ohmachi.smooth(spectra)

    def explode(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("the matrix was rebuilt instead of reused")

    original = konno_ohmachi.smoothing_matrix
    konno_ohmachi.smoothing_matrix = explode  # ty: ignore[invalid-assignment]
    try:
        assert konno_ohmachi.smooth(spectra) == pytest.approx(first, rel=1e-12)
    finally:
        konno_ohmachi.smoothing_matrix = original


def test_clear_matrix_cache_releases_matrices(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Clearing genuinely empties the store rather than only resetting a counter."""
    konno_ohmachi.smooth(spectra)
    assert konno_ohmachi._MATRICES

    konno_ohmachi.clear_matrix_cache()
    assert not konno_ohmachi._MATRICES
    assert konno_ohmachi._RESIDENT_BYTES == 0


def test_matrices_are_evicted_to_stay_inside_the_budget(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Holding two matrices that do not both fit evicts the older one."""
    # One 65-bin matrix is 16.9 kB; allow a little over one.
    monkeypatch.setenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, str(65 * 65 * 4 + 1))
    konno_ohmachi._matrix(65, 40.0)
    konno_ohmachi._matrix(65, 20.0)

    assert list(konno_ohmachi._MATRICES) == [(65, 20.0)]
    assert konno_ohmachi._RESIDENT_BYTES == 65 * 65 * 4


def test_blocked_application_matches_unblocked(
    spectra: npt.NDArray[np.float64], monkeypatch: pytest.MonkeyPatch
) -> None:
    """Blocking over the contraction index does not change the result."""
    unblocked = konno_ohmachi.smooth(spectra)

    konno_ohmachi.clear_matrix_cache()
    # One row per block, so every block boundary is exercised.
    monkeypatch.setattr(konno_ohmachi, "KONNO_BLOCK_BYTES", 1)
    monkeypatch.setenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, "1")

    assert konno_ohmachi.smooth(spectra) == pytest.approx(unblocked, rel=1e-6)


def test_concurrent_smoothing_is_consistent(
    spectra: npt.NDArray[np.float64],
) -> None:
    """Several threads racing on one size all get the same answer."""
    with ThreadPoolExecutor(max_workers=8) as pool:
        results = list(pool.map(lambda _: konno_ohmachi.smooth(spectra), range(8)))

    for result in results[1:]:
        assert result == pytest.approx(results[0], rel=1e-12)


def test_memory_budget_and_scratch_directory_defaults(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Both settings read the environment at call time, and have defaults."""
    monkeypatch.delenv(konno_ohmachi.SCRATCH_DIRECTORY_VARIABLE)
    monkeypatch.delenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, raising=False)
    assert konno_ohmachi.memory_budget() == konno_ohmachi.DEFAULT_MEMORY_BUDGET
    assert konno_ohmachi.resolve_scratch_directory().is_dir()

    monkeypatch.setenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, "12345")
    monkeypatch.setenv(konno_ohmachi.SCRATCH_DIRECTORY_VARIABLE, "/from-env")
    assert konno_ohmachi.memory_budget() == 12345
    assert konno_ohmachi.resolve_scratch_directory() == Path("/from-env")

    # An explicit directory beats the environment.
    assert konno_ohmachi.resolve_scratch_directory(Path("/explicit")) == Path(
        "/explicit"
    )


def test_scratch_directory_argument_is_used(
    spectra: npt.NDArray[np.float64],
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The kwarg overrides the environment for where a spill is built."""
    monkeypatch.setenv(konno_ohmachi.MEMORY_BUDGET_VARIABLE, "1")
    monkeypatch.setenv(konno_ohmachi.SCRATCH_DIRECTORY_VARIABLE, str(tmp_path / "env"))
    chosen = tmp_path / "explicit"

    smoothed = konno_ohmachi.smooth(spectra, scratch_directory=chosen)

    # The chosen directory was created and used; the environment one never was.
    assert chosen.is_dir()
    assert not (tmp_path / "env").exists()
    # Unlinked while open, so it is left empty.
    assert list(chosen.iterdir()) == []
    assert isinstance(konno_ohmachi._MATRICES[(65, 40.0)], np.memmap)
    assert np.isfinite(smoothed).all()


def test_failed_spill_leaves_no_partial_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A build that dies partway removes its file rather than leaving a stub."""

    def fail(*_args: object, **_kwargs: object) -> None:
        raise OSError("no space left on device")

    monkeypatch.setattr(konno_ohmachi._core, "_konno_ohmachi_matrix_rows", fail)

    assert konno_ohmachi._spilled_matrix(65, 40.0, tmp_path) is None
    assert list(tmp_path.iterdir()) == []
