"""Script for generating the Konno matrices"""

from pathlib import Path
from typing import Annotated

import numpy as np
import typer
from obspy.signal.konnoohmachismoothing import calculate_smoothing_matrix

from qcore import cli

app = typer.Typer()


@cli.from_docstring(app)
def main(
    output_dir: Annotated[
        Path,
        typer.Argument(
            exists=False,
            file_okay=False,
        ),
    ],
    num_to_gen: Annotated[int, typer.Option()] = 14,
    bandwidth: Annotated[int, typer.Option()] = 40,
):
    """Generate the Konno matrices for different window sizes.

    Parameters
    ----------
    output_dir : Path
        Destination directory for the Konno matrices.
    num_to_gen : int
        Number of KO matrix generations to compute. The largest matrix has `4 * 2 ** num_to_gen` rows and columns.
    bandwidth : int
        Bandwidth of the Konno-Ohmachi smoothing window.

    """
    for i in range(num_to_gen):
        n = 8 * 2**i
        # NOTE: The KO calculation relies on the ratio f / f_c. Frequencies 'f' generated by
        # np.fft.fftfreq(n, dt) are proportional to 1/dt (f = k / (n*dt)).
        # KO matrices have values sin(b * log_10(f/f_c)) / (b * log_10(f/f_c)]^4 where b = bandwidth, f = frequency, f_c = center frequency.
        # A center frequency 'f_c' that scales the same way (also proportional to 1/dt)
        # cancels the 'dt' factor in the ratio f / f_c, so the KO matrix calculation comes out
        # independent of the specific value of 'dt' (sample spacing). This code takes the default `dt = 1`.
        ft_freq = np.fft.rfftfreq(n * 2).astype(np.float32)
        cur_konno = calculate_smoothing_matrix(
            ft_freq, bandwidth=bandwidth, normalize=True
        )
        cur_konno = np.asfortranarray(cur_konno)
        np.save(output_dir / f"KO_{n}.npy", cur_konno)


if __name__ == "__main__":
    app()
