#----------------------------------------------------------------------------------#
# ModelCodePastedFromExcelVBA.tcl
#	This is the file into which we paste all of the model code generated by Excel VBA
#	to create the archetype models.
#
# Units: kips, in, sec
#
# This file developed by: Curt Haselton of Stanford University
# Date: 10 June 2006
#
# Other files used in developing this model:
#	None
#----------------------------------------------------------------------------------#



# Pasted from Excel 4story_ID1008_v.13 on 7-21-06 by Brian Dean

#########################################################################################################################
########### Start of code pasted from Excel Structural Design Sheet output to ModelCodePastedFromExcelVBA.tcl ###########
########### This code was created using a Visual Basic script in the Structural Design Excel sheet ######################
########### Created by Curt B. Haselton, Stanford University, June 10, 2006 #############################################
#########################################################################################################################

#########################################################################################################################
### DEFINE MATERIALS
 
# Define Joint Shear Panel Materials
     uniaxialMaterial Elastic 40501 5150022.73615486 
     uniaxialMaterial Elastic 40502 5150022.73615486 
     uniaxialMaterial Elastic 40503 5150022.73615486 
     uniaxialMaterial Elastic 40504 5150022.73615486 
 
     uniaxialMaterial Elastic 40401 5150022.73615486 
     uniaxialMaterial Elastic 40402 5150022.73615486 
     uniaxialMaterial Elastic 40403 5150022.73615486 
     uniaxialMaterial Elastic 40404 5150022.73615486 
 
     uniaxialMaterial Elastic 40301 5150022.73615486 
     uniaxialMaterial Elastic 40302 5150022.73615486 
     uniaxialMaterial Elastic 40303 5150022.73615486 
     uniaxialMaterial Elastic 40304 5150022.73615486 
 
     uniaxialMaterial Elastic 40201 5150022.73615486 
     uniaxialMaterial Elastic 40202 5150022.73615486 
     uniaxialMaterial Elastic 40203 5150022.73615486 
     uniaxialMaterial Elastic 40204 5150022.73615486 
 
 
# Define the Column Plastic Hinge Materials
     #                               matTag EIeff mYPos mYNeg mcOverMy thetaCapPos thetaCapNeg thetaPC lambda c resStrRatio stiffFactor1 stiffFactor2 eleLength
     CreateIbarraMaterial     304011   27538316.019717   3224.46050113988   -3224.46050113988   1.20772852620201    6.75567211335751E-02   -6.75567211335751E-02   0.1     162.091702524934     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     304021   27538316.019717   4346.23416178285   -4346.23416178285   1.20547818432172    6.73755051342885E-02   -6.73755051342885E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     304031   27538316.019717   4346.23416178285   -4346.23416178285   1.20547818432172    6.73755051342885E-02   -6.73755051342885E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     304041   27538316.019717   3224.46050113988   -3224.46050113988   1.20772852620201    6.75567211335751E-02   -6.75567211335751E-02   0.1     162.091702524934     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
 
     CreateIbarraMaterial     303011   27538316.019717   3555.46678263549   -3555.46678263549   1.20547818432172    6.56041320171346E-02   -6.56041320171346E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     303021   27538316.019717   4984.35320063925   -4984.35320063925   1.20099007182996    6.35370864765282E-02   -6.35370864765282E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     303031   27538316.019717   4984.35320063925   -4984.35320063925   1.20099007182996    6.35370864765282E-02   -6.35370864765282E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     303041   27538316.019717   3555.46678263549   -3555.46678263549   1.20547818432172    6.56041320171346E-02   -6.56041320171346E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
 
     CreateIbarraMaterial     302011   27538316.019717   4304.88223388092   -4304.88223388092   1.20323203546863    0.064628529925815   -0.064628529925815   0.1     155.438903810143     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     302021   27538316.019717   6024.35823460392   -6024.35823460392   1.19651866901741    6.07831230682183E-02   -6.07831230682183E-02   0.1     145.968160930339     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     302031   27538316.019717   6024.35823460392   -6024.35823460392   1.19651866901741    6.07831230682183E-02   -6.07831230682183E-02   0.1     145.968160930339     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
     CreateIbarraMaterial     302041   27538316.019717   4304.88223388092   -4304.88223388092   1.20323203546863    0.064628529925815   -0.064628529925815   0.1     155.438903810143     $c $resStrRatio $stiffFactor1 $stiffFactor2     132 
 
     CreateIbarraMaterial     301011   27538316.019717   4623.35596821944   -4623.35596821944   1.20099007182996    6.27605741987279E-02   -6.27605741987279E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     156 
     CreateIbarraMaterial     301021   29542507.1909881   6630.54352551691   -6630.54352551691   1.19206391367229    0.057320275951941   -0.057320275951941   0.1     139.338189777811     $c $resStrRatio $stiffFactor1 $stiffFactor2     156 
     CreateIbarraMaterial     301031   29542507.1909881   6630.54352551691   -6630.54352551691   1.19206391367229    0.057320275951941   -0.057320275951941   0.1     139.338189777811     $c $resStrRatio $stiffFactor1 $stiffFactor2     156 
     CreateIbarraMaterial     301041   27538316.019717   4623.35596821944   -4623.35596821944   1.20099007182996    6.27605741987279E-02   -6.27605741987279E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     156 
 
 
# Define the Beam Plastic Hinge Materials
#     The trailing 1 means a positively oriented material, while the trailing 2 is the same material flipped upside-down (for use on the left side of a joint element)
     #                               matTag EIeff mYPos mYNeg mcOverMy thetaCapPos thetaCapNeg thetaPC lambda c resStrRatio stiffFactor1 stiffFactor2 eleLength
     CreateIbarraMaterial     205011   93533595.9994867   2013.58321334698   -4263.57317144846   1.20998306893691    3.90290402282413E-02   -0.064134649085204   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205012   93533595.9994867   4263.57317144846   -2013.58321334698   1.20998306893691    0.064134649085204   -3.90290402282413E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205021   93533595.9994867   2013.58321334698   -4263.57317144846   1.20998306893691    3.90290402282413E-02   -0.064134649085204   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205022   93533595.9994867   4263.57317144846   -2013.58321334698   1.20998306893691    0.064134649085204   -3.90290402282413E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205031   93533595.9994867   2013.58321334698   -4263.57317144846   1.20998306893691    3.90290402282413E-02   -0.064134649085204   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205032   93533595.9994867   4263.57317144846   -2013.58321334698   1.20998306893691    0.064134649085204   -3.90290402282413E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     204011   93533595.9994867   2011.65254747246   -5155.74304187921   1.20998306893691    3.82360663852428E-02   -6.70946919342063E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204012   93533595.9994867   5155.74304187921   -2011.65254747246   1.20998306893691    6.70946919342063E-02   -3.82360663852428E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204021   93533595.9994867   2011.65254747246   -5155.74304187921   1.20998306893691    3.82360663852428E-02   -6.70946919342063E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204022   93533595.9994867   5155.74304187921   -2011.65254747246   1.20998306893691    6.70946919342063E-02   -3.82360663852428E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204031   93533595.9994867   2011.65254747246   -5155.74304187921   1.20998306893691    3.82360663852428E-02   -6.70946919342063E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204032   93533595.9994867   5155.74304187921   -2011.65254747246   1.20998306893691    6.70946919342063E-02   -3.82360663852428E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     203011   93533595.9994867   2350.76944131095   -6041.23596172343   1.20998306893691    3.91794432861957E-02   -6.77202837559299E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203012   93533595.9994867   6041.23596172343   -2350.76944131095   1.20998306893691    6.77202837559299E-02   -3.91794432861957E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203021   93533595.9994867   2350.76944131095   -6041.23596172343   1.20998306893691    3.91794432861957E-02   -6.77202837559299E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203022   93533595.9994867   6041.23596172343   -2350.76944131095   1.20998306893691    6.77202837559299E-02   -3.91794432861957E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203031   93533595.9994867   2350.76944131095   -6041.23596172343   1.20998306893691    3.91794432861957E-02   -6.77202837559299E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203032   93533595.9994867   6041.23596172343   -2350.76944131095   1.20998306893691    6.77202837559299E-02   -3.91794432861957E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     202011   93533595.9994867   2681.27069924609   -6482.96093308874   1.20998306893691    4.02912332703641E-02   -6.72586404737499E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202012   93533595.9994867   6482.96093308874   -2681.27069924609   1.20998306893691    6.72586404737499E-02   -4.02912332703641E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202021   93533595.9994867   2681.27069924609   -6482.96093308874   1.20998306893691    4.02912332703641E-02   -6.72586404737499E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202022   93533595.9994867   6482.96093308874   -2681.27069924609   1.20998306893691    6.72586404737499E-02   -4.02912332703641E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202031   93533595.9994867   2681.27069924609   -6482.96093308874   1.20998306893691    4.02912332703641E-02   -6.72586404737499E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202032   93533595.9994867   6482.96093308874   -2681.27069924609   1.20998306893691    6.72586404737499E-02   -4.02912332703641E-02   0.1     174.869243105311     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
 
# Define the Elastic Footing Rotational Stiffness Materials (this includes link beam and footing-soil stiffness
     uniaxialMaterial Elastic    601  12800000 
     uniaxialMaterial Elastic    602  12800000 
     uniaxialMaterial Elastic    603  12800000 
     uniaxialMaterial Elastic    604  12800000 
 
#########################################################################################################################
### DEFINE NODES
 
# Define the Elastic Footing Rotational Stiffness Materials (this includes link beam and footing-soil stiffness
      #   nodeNum   X   Y
     node   201011  0 0 
     node   201012  0 0 
     node   201013  0 0 
     node   201021  240 0 
     node   201022  240 0 
     node   201023  240 0 
     node   201031  480 0 
     node   201032  480 0 
     node   201033  480 0 
     node   201041  720 0 
     node   201042  720 0 
     node   201043  720 0 
 
# Define the nodes around all of the joints in the primary frame
      #   nodeNum   X   Y
     node   205011  0 624 
     node   205012  11 636 
     node   205013  0 648 
     node   205014  -11 636 
     node   205021  240 624 
     node   205022  251 636 
     node   205023  240 648 
     node   205024  229 636 
     node   205031  480 624 
     node   205032  491 636 
     node   205033  480 648 
     node   205034  469 636 
     node   205041  720 624 
     node   205042  731 636 
     node   205043  720 648 
     node   205044  709 636 
 
     node   204011  0 468 
     node   204012  11 480 
     node   204013  0 492 
     node   204014  -11 480 
     node   204021  240 468 
     node   204022  251 480 
     node   204023  240 492 
     node   204024  229 480 
     node   204031  480 468 
     node   204032  491 480 
     node   204033  480 492 
     node   204034  469 480 
     node   204041  720 468 
     node   204042  731 480 
     node   204043  720 492 
     node   204044  709 480 
 
     node   203011  0 312 
     node   203012  11 324 
     node   203013  0 336 
     node   203014  -11 324 
     node   203021  240 312 
     node   203022  251 324 
     node   203023  240 336 
     node   203024  229 324 
     node   203031  480 312 
     node   203032  491 324 
     node   203033  480 336 
     node   203034  469 324 
     node   203041  720 312 
     node   203042  731 324 
     node   203043  720 336 
     node   203044  709 324 
 
     node   202011  0 156 
     node   202012  11 168 
     node   202013  0 180 
     node   202014  -11 168 
     node   202021  240 156 
     node   202022  251 168 
     node   202023  240 180 
     node   202024  229 168 
     node   202031  480 156 
     node   202032  491 168 
     node   202033  480 180 
     node   202034  469 168 
     node   202041  720 156 
     node   202042  731 168 
     node   202043  720 180 
     node   202044  709 168 
 
# Define the nodes around all of the joints in the primary frame
node 3051 840 648
node 3041 840 492
node 3043 840 492
equalDOF 3043 3041 1 2
node 3031 840 336
node 3033 840 336
equalDOF 3033 3031 1 2
node 3021 840 180
node 3023 840 180
equalDOF 3023 3021 1 2
node 3013 840 0
 
#########################################################################################################################
### DEFINE FIXITIES
 
# Define the fixities at the bases of the columns of the primary lateral frame
#       node    DX DY RZ
     fix    201011    1  1  1 
     fix    201021    1  1  1 
     fix    201031    1  1  1 
     fix    201041    1  1  1 
 
# Define the fixity at the baseof the leaning column
#       node    DX DY RZ
fix 3013 1 1 0
 
#########################################################################################################################
### DEFINE ELEMENTS
 
# Define the column elements
             ##                 tag     node1   node2       EA      EofUnity    EI          geomTransf  
     element elasticBeamColumn   30401 204013 205011   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
     element elasticBeamColumn   30402 204023 205021   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30403 204033 205031   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30404 204043 205041   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
 
     element elasticBeamColumn   30301 203013 204011   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
     element elasticBeamColumn   30302 203023 204021   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30303 203033 204031   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30304 203043 204041   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
 
     element elasticBeamColumn   30201 202013 203011   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
     element elasticBeamColumn   30202 202023 203021   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30203 202033 203031   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30204 202043 203041   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
 
     element elasticBeamColumn   30101 201013 202011   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
     element elasticBeamColumn   30102 201023 202021   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30103 201033 202031   $EAcol  $EOfUnity   29542507.1909881  $primaryGeomTransT 
     element elasticBeamColumn   30104 201043 202041   $EAcol  $EOfUnity   27538316.019717  $primaryGeomTransT 
 
# Define the beam elements
             ##                 tag     node1   node2       EA      EofUnity    EI          geomTransf  
     element elasticBeamColumn   20501 205012 205024   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20502 205022 205034   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20503 205032 205044   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
 
     element elasticBeamColumn   20401 204012 204024   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20402 204022 204034   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20403 204032 204044   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
 
     element elasticBeamColumn   20301 203012 203024   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20302 203022 203034   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20303 203032 203044   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
 
     element elasticBeamColumn   20201 202012 202024   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20202 202022 202034   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
     element elasticBeamColumn   20203 202032 202044   $EABm  $EOfUnity   93533595.9994867  $primaryGeomTransT 
 
 
# Define the column base rotational spring (both elastic foundation springs and column base PH springs)
     ##  eleID nodeR nodeC matID 
     rotSpring2D     6011    201011  201012  601 
     rotSpring2D     6012    201012  201013  301011 
 
     rotSpring2D     6021    201021  201022  602 
     rotSpring2D     6022    201022  201023  301021 
 
     rotSpring2D     6031    201031  201032  603 
     rotSpring2D     6032    201032  201033  301031 
 
     rotSpring2D     6041    201041  201042  604 
     rotSpring2D     6042    201042  201043  301041 
 
# Define the joint elements
    #                  tag         n1       n2     n3     n4       centerNode  PH1     PH2     PH3     PH4     shearPanel  largeDisp
     element Joint2D     40501       205011  205012  205013  205014  205015      304011   205011   49999  49999  40501       $lrgDsp 
     element Joint2D     40502       205021  205022  205023  205024  205025      304021   205021   49999  205012  40502       $lrgDsp 
     element Joint2D     40503       205031  205032  205033  205034  205035      304031   205031   49999  205022  40503       $lrgDsp 
     element Joint2D     40504       205041  205042  205043  205044  205045      304041   49999   49999  205032  40504       $lrgDsp 
 
     element Joint2D     40401       204011  204012  204013  204014  204015      303011   204011   304011  49999  40401       $lrgDsp 
     element Joint2D     40402       204021  204022  204023  204024  204025      303021   204021   304021  204012  40402       $lrgDsp 
     element Joint2D     40403       204031  204032  204033  204034  204035      303031   204031   304031  204022  40403       $lrgDsp 
     element Joint2D     40404       204041  204042  204043  204044  204045      303041   49999   304041  204032  40404       $lrgDsp 
 
     element Joint2D     40301       203011  203012  203013  203014  203015      302011   203011   303011  49999  40301       $lrgDsp 
     element Joint2D     40302       203021  203022  203023  203024  203025      302021   203021   303021  203012  40302       $lrgDsp 
     element Joint2D     40303       203031  203032  203033  203034  203035      302031   203031   303031  203022  40303       $lrgDsp 
     element Joint2D     40304       203041  203042  203043  203044  203045      302041   49999   303041  203032  40304       $lrgDsp 
 
     element Joint2D     40201       202011  202012  202013  202014  202015      301011   202011   302011  49999  40201       $lrgDsp 
     element Joint2D     40202       202021  202022  202023  202024  202025      301021   202021   302021  202012  40202       $lrgDsp 
     element Joint2D     40203       202031  202032  202033  202034  202035      301031   202031   302031  202022  40203       $lrgDsp 
     element Joint2D     40204       202041  202042  202043  202044  202045      301041   49999   302041  202032  40204       $lrgDsp 
 
# Define the leaning column and horizintal rigid link elements
element elasticBeamColumn 5041 3043 3051 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5031 3033 3041 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5021 3023 3031 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5011 3013 3021 $Acol $E_strut $I_strut $primaryGeomTransT
 
element truss 5052 205043 3051 $A_strut $strutMatT
element truss 5042 204043 3041 $A_strut $strutMatT
element truss 5032 203043 3031 $A_strut $strutMatT
element truss 5022 202043 3021 $A_strut $strutMatT
 
#########################################################################################################################
### DEFINE GRAVITY LOADS
 
      pattern Plain 1 Linear {
             # Distributed beam element loads
             eleLoad -ele  20501 20502 20503 20401 20402 20403 20301 20302 20303 20201 20202 20203   -type -beamUniform   -0.32275
             # Point gravity loads on leaning column
             #        node    X   Y           M
load 3051 0.0 -28.402 0.0
load 3043 0.0 -28.402 0.0
load 3033 0.0 -28.402 0.0
load 3023 0.0 -28.402 0.0
      }
 
#########################################################################################################################
### DEFINE MASSES
 
# Define small masses at all nodes as the column-foundation connection
      #       nodeNum    X    Y     Rotation
     mass   201011    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201012    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201013    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201021    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201022    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201023    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201031    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201032    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201033    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201041    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201042    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201043    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
 
# Define small masses as the nodes around all of the joints in the primary frame
mass 3051 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3041 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3043 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3031 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3033 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3021 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3023 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3013 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
 
# Define building masses
      #       nodeNum    X    Y     Rotation
     mass    205011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    204011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    203011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    202011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
 # Check: Total mass applied to building is: 2.39074074074074.  This was summed in the VB loop when mass was applied. This does not include small masses applied for convergence. 
 #########################################################################################################################

### DEFINE ADDITIONAL INFORMATION
# Define the number of stories in the frame
set num_stories 4

# Define the control nodes used to compute story drifts
set ctrl_nodes {
    201023
    202023
    203023
    204023
    205023
}

#########################################################################################################################
### APPLY GRAVITY LOAD ###
#########################################################################################################################

# Recorders for gravity
 file mkdir $Output_path/gravity_drift
 file mkdir $Output_path/gravity_disp
 
# --Define the story drift recorders--
for {set story 1} {$story <= $num_stories} {incr story} {
   recorder Drift -file $Output_path/gravity_drift/gr_drift_story${story}.out -time -iNode [lindex $ctrl_nodes \
            [expr {$story - 1}]] -jNode [lindex $ctrl_nodes $story] -dof 1 -perpDirn 2
}

# Displacement
for {set story 1} {$story <= $num_stories} {incr story} {
    recorder Node -file $Output_path/gravity_disp/gr_disp_story${story}.out -time -node [lindex $ctrl_nodes $story] -dof 1 disp
}

set numsteps_grav 10
set tol 1e-12
set maxiter 20

constraints Transformation
numberer RCM
system SparseGEN
test RelativeEnergyIncr $tol $maxiter
algorithm Newton
integrator LoadControl [expr {1.0/$numsteps_grav}]
analysis Static

if {[analyze $numsteps_grav]} {puts "Application of gravity load failed"}

loadConst -time 0.0
wipeAnalysis
remove recorders

### DEFINE DAMPING OBJECTS
set eigenvalues [eigen -fullGenLapack [lindex $modes 1]]
set periodForRayleighDamping_1 [expr {2.0*$pi/sqrt([lindex $eigenvalues [lindex $modes 0]-1])}]
set periodForRayleighDamping_2 [expr {2.0*$pi/sqrt([lindex $eigenvalues [lindex $modes 1]-1])}]
 
# Define damping for all beams and all columns (i.e. elastic elements), but not on the joints b/c they have the nonlinearity in them.  This is the approach proposed by Medina.  Compute the damping paramters based on Chopra text page 457.
      set omegaI [expr (2.0 * $pi) / $periodForRayleighDamping_1]
      set omegaJ [expr (2.0 * $pi) / ($periodForRayleighDamping_2)]
      set alpha1Coeff [expr (2.0 * $omegaI * $omegaJ) / ($omegaI + $omegaJ)]
      set alpha2Coeff [expr (2.0) / ($omegaI + $omegaJ)]
      set alpha1  [expr $alpha1Coeff * $dampRat * $dampRatF]
      set alpha2  [expr $alpha2Coeff * $dampRat * $dampRatF]
      set alpha2ToUse [expr 1.1 * $alpha2];   # 1.1 factor is becuase we apply to only LE elements
      region 1 -eleRange  20201   30404   -rayleigh $alpha1 0 $alpha2ToUse 0;    # Initial stiffness"
#--------------------------------------------------------------------------------------------------------------------------------------------------------
 
