#----------------------------------------------------------------------------------#
# ModelCodePastedFromExcelVBA.tcl
#	This is the file into which we paste all of the model code generated by Excel VBA
#	to create the archetype models.
#
# Units: kips, in, sec
#
# This file developed by: Curt Haselton of Stanford University
# Date: 10 June 2006
#
# Other files used in developing this model:
#	None
#----------------------------------------------------------------------------------#



# Pasted from Excel 12story_ID1014_v.61 on 7-20-06 by Brian Dean

#########################################################################################################################
########### Start of code pasted from Excel Structural Design Sheet output to ModelCodePastedFromExcelVBA.tcl ###########
########### This code was created using a Visual Basic script in the Structural Design Excel sheet ######################
########### Created by Curt B. Haselton, Stanford University, June 10, 2006 #############################################
#########################################################################################################################

#########################################################################################################################
### DEFINE MATERIALS
 
# Define Joint Shear Panel Materials
     uniaxialMaterial Elastic 41301 4720854.17480862 
     uniaxialMaterial Elastic 41302 4720854.17480862 
     uniaxialMaterial Elastic 41303 4720854.17480862 
     uniaxialMaterial Elastic 41304 4720854.17480862 
 
     uniaxialMaterial Elastic 41201 4720854.17480862 
     uniaxialMaterial Elastic 41202 4720854.17480862 
     uniaxialMaterial Elastic 41203 4720854.17480862 
     uniaxialMaterial Elastic 41204 4720854.17480862 
 
     uniaxialMaterial Elastic 41101 4720854.17480862 
     uniaxialMaterial Elastic 41102 4720854.17480862 
     uniaxialMaterial Elastic 41103 4720854.17480862 
     uniaxialMaterial Elastic 41104 4720854.17480862 
 
     uniaxialMaterial Elastic 41001 4720854.17480862 
     uniaxialMaterial Elastic 41002 4720854.17480862 
     uniaxialMaterial Elastic 41003 4720854.17480862 
     uniaxialMaterial Elastic 41004 4720854.17480862 
 
     uniaxialMaterial Elastic 40901 6008359.85884734 
     uniaxialMaterial Elastic 40902 6008359.85884734 
     uniaxialMaterial Elastic 40903 6008359.85884734 
     uniaxialMaterial Elastic 40904 6008359.85884734 
 
     uniaxialMaterial Elastic 40801 6008359.85884734 
     uniaxialMaterial Elastic 40802 6008359.85884734 
     uniaxialMaterial Elastic 40803 6008359.85884734 
     uniaxialMaterial Elastic 40804 6008359.85884734 
 
     uniaxialMaterial Elastic 40701 6008359.85884734 
     uniaxialMaterial Elastic 40702 6008359.85884734 
     uniaxialMaterial Elastic 40703 6008359.85884734 
     uniaxialMaterial Elastic 40704 6008359.85884734 
 
     uniaxialMaterial Elastic 40601 6008359.85884734 
     uniaxialMaterial Elastic 40602 6008359.85884734 
     uniaxialMaterial Elastic 40603 6008359.85884734 
     uniaxialMaterial Elastic 40604 6008359.85884734 
 
     uniaxialMaterial Elastic 40501 6008359.85884734 
     uniaxialMaterial Elastic 40502 6008359.85884734 
     uniaxialMaterial Elastic 40503 6008359.85884734 
     uniaxialMaterial Elastic 40504 6008359.85884734 
 
     uniaxialMaterial Elastic 40401 6008359.85884734 
     uniaxialMaterial Elastic 40402 6008359.85884734 
     uniaxialMaterial Elastic 40403 6008359.85884734 
     uniaxialMaterial Elastic 40404 6008359.85884734 
 
     uniaxialMaterial Elastic 40301 6008359.85884734 
     uniaxialMaterial Elastic 40302 6008359.85884734 
     uniaxialMaterial Elastic 40303 6008359.85884734 
     uniaxialMaterial Elastic 40304 6008359.85884734 
 
     uniaxialMaterial Elastic 40201 6008359.85884734 
     uniaxialMaterial Elastic 40202 6008359.85884734 
     uniaxialMaterial Elastic 40203 6008359.85884734 
     uniaxialMaterial Elastic 40204 6008359.85884734 
 
 
# Define the Column Plastic Hinge Materials
     #                               matTag EIeff mYPos mYNeg mcOverMy thetaCapPos thetaCapNeg thetaPC lambda c resStrRatio stiffFactor1 stiffFactor2 eleLength
     CreateIbarraMaterial     312011   27538316.019717   3408.62392346075   -3408.62392346075   1.20772852620201    6.79733629316178E-02   -6.79733629316178E-02   0.1     162.091702524934     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     312021   27538316.019717   4467.53365806117   -4467.53365806117   1.20547818432172    6.76522372966836E-02   -6.76522372966836E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     312031   27538316.019717   4467.53365806117   -4467.53365806117   1.20547818432172    6.76522372966836E-02   -6.76522372966836E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     312041   27538316.019717   3408.62392346075   -3408.62392346075   1.20772852620201    6.79733629316178E-02   -6.79733629316178E-02   0.1     162.091702524934     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
 
     CreateIbarraMaterial     311011   27538316.019717   3738.34352755544   -3738.34352755544   1.20547818432172    6.60087316345229E-02   -6.60087316345229E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     311021   27538316.019717   5104.578913626   -5104.578913626   1.20099007182996    6.37980530592333E-02   -6.37980530592333E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     311031   27538316.019717   5104.578913626   -5104.578913626   1.20099007182996    6.37980530592333E-02   -6.37980530592333E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     311041   27538316.019717   3738.34352755544   -3738.34352755544   1.20547818432172    6.60087316345229E-02   -6.60087316345229E-02   0.1     158.730452519974     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
 
     CreateIbarraMaterial     310011   27538316.019717   4425.81374027549   -4425.81374027549   1.20323203546863    6.48939794063516E-02   -6.48939794063516E-02   0.1     155.438903810143     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     310021   27538316.019717   6322.74187144614   -6322.74187144614   1.19651866901741    6.14091850257371E-02   -6.14091850257371E-02   0.1     145.968160930339     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     310031   27538316.019717   6322.74187144614   -6322.74187144614   1.19651866901741    6.14091850257371E-02   -6.14091850257371E-02   0.1     145.968160930339     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
     CreateIbarraMaterial     310041   27538316.019717   4425.81374027549   -4425.81374027549   1.20323203546863    6.48939794063516E-02   -6.48939794063516E-02   0.1     155.438903810143     $c $resStrRatio $stiffFactor1 $stiffFactor2     134 
 
     CreateIbarraMaterial     309011   27538316.019717   4743.74424409589   -4743.74424409589   1.20099007182996    6.30183514039088E-02   -6.30183514039088E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     158 
     CreateIbarraMaterial     309021   29864383.6119977   7343.75749764822   -7343.75749764822   1.19206391367229    5.87474537775237E-02   -5.87474537775237E-02   0.1     138.807242336938     $c $resStrRatio $stiffFactor1 $stiffFactor2     158 
     CreateIbarraMaterial     309031   29864383.6119977   7343.75749764822   -7343.75749764822   1.19206391367229    5.87474537775237E-02   -5.87474537775237E-02   0.1     138.807242336938     $c $resStrRatio $stiffFactor1 $stiffFactor2     158 
     CreateIbarraMaterial     309041   27538316.019717   4743.74424409589   -4743.74424409589   1.20099007182996    6.30183514039088E-02   -6.30183514039088E-02   0.1     152.215611019307     $c $resStrRatio $stiffFactor1 $stiffFactor2     158 
 
     CreateIbarraMaterial     308011   29702918.6946222   5656.54959749781   -5656.54959749781   1.19875228560746    6.24640752707776E-02   -6.24640752707776E-02   0.1     142.661912458514     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     308021   35873094.6087589   7699.24572176184   -7699.24572176184   1.18762574381446    5.49482735432998E-02   -5.49482735432998E-02   0.1     128.28673469507     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     308031   35873094.6087589   7699.24572176184   -7699.24572176184   1.18762574381446    5.49482735432998E-02   -5.49482735432998E-02   0.1     128.28673469507     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     308041   29702918.6946222   5656.54959749781   -5656.54959749781   1.19875228560746    6.24640752707776E-02   -6.24640752707776E-02   0.1     142.661912458514     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     307011   30936953.8774495   5845.26048504048   -5845.26048504048   1.19651866901741    6.04105537470377E-02   -6.04105537470377E-02   0.1     139.657030255106     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     307021   38341164.9744136   8223.19792681746   -8223.19792681746   1.18320409769455    5.17117516306078E-02   -5.17117516306078E-02   0.1     122.966728552844     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     307031   38341164.9744136   8223.19792681746   -8223.19792681746   1.18320409769455    5.17117516306078E-02   -5.17117516306078E-02   0.1     122.966728552844     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     307041   30936953.8774495   5845.26048504048   -5845.26048504048   1.19651866901741    6.04105537470377E-02   -6.04105537470377E-02   0.1     139.657030255106     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     306011   32170989.0602769   6150.32224668229   -6150.32224668229   1.19428921429059    5.86645100109692E-02   -5.86645100109692E-02   0.1     136.718948091325     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     306021   40809235.3400683   8560.56855688937   -8560.56855688937   1.17879891379307    4.83675681462289E-02   -4.83675681462289E-02   0.1     117.873698722962     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     306031   40809235.3400683   8560.56855688937   -8560.56855688937   1.17879891379307    4.83675681462289E-02   -4.83675681462289E-02   0.1     117.873698722962     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     306041   32170989.0602769   6150.32224668229   -6150.32224668229   1.19428921429059    5.86645100109692E-02   -5.86645100109692E-02   0.1     136.718948091325     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     305011   33405024.2431042   6452.20031452889   -6452.20031452889   1.19206391367229    5.69689321047792E-02   -5.69689321047792E-02   0.1     133.84572937498     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     305021   43277305.705723   9126.17636115189   -9126.17636115189   1.17441013081959    4.56120418517255E-02   -4.56120418517255E-02   9.10642226687245E-02     112.996660568205     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     305031   43277305.705723   9126.17636115189   -9126.17636115189   1.17441013081959    4.56120418517255E-02   -4.56120418517255E-02   9.10642226687245E-02     112.996660568205     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     305041   33405024.2431042   6452.20031452889   -6452.20031452889   1.19206391367229    5.69689321047792E-02   -5.69689321047792E-02   0.1     133.84572937498     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     304011   34639059.4259316   6513.64247337143   -6513.64247337143   1.1898427594222    5.48706937252772E-02   -5.48706937252772E-02   0.1     131.035560741121     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     304021   45745376.0713777   9328.59901443761   -9328.59901443761   1.17003768771184    4.24878140992795E-02   -4.24878140992795E-02   8.14814766460649E-02     108.325465034554     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     304031   45745376.0713777   9328.59901443761   -9328.59901443761   1.17003768771184    4.24878140992795E-02   -4.24878140992795E-02   8.14814766460649E-02     108.325465034554     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     304041   34639059.4259316   6513.64247337143   -6513.64247337143   1.1898427594222    5.48706937252772E-02   -5.48706937252772E-02   0.1     131.035560741121     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     303011   35873094.6087589   6809.988576894   -6809.988576894   1.18762574381446    5.32847683342614E-02   -5.32847683342614E-02   0.1     128.28673469507     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     303021   48213446.4370324   10570.393296044   -10570.393296044   1.16568152363493    4.00672605458616E-02   -4.00672605458616E-02   7.29071290771961E-02     103.850661782969     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     303031   48213446.4370324   10570.393296044   -10570.393296044   1.16568152363493    4.00672605458616E-02   -4.00672605458616E-02   7.29071290771961E-02     103.850661782969     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     303041   35873094.6087589   6809.988576894   -6809.988576894   1.18762574381446    5.32847683342614E-02   -5.32847683342614E-02   0.1     128.28673469507     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     302011   37107129.7915863   7103.57103485782   -7103.57103485782   1.18541285913761    5.17446808792203E-02   -5.17446808792203E-02   0.1     125.597635644271     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     302021   50681516.8026871   10626.3559487607   -10626.3559487607   1.16134157798044    3.77846072264089E-02   -3.77846072264089E-02   6.52350655519892E-02     99.5633987623392     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     302031   50681516.8026871   10626.3559487607   -10626.3559487607   1.16134157798044    3.77846072264089E-02   -3.77846072264089E-02   6.52350655519892E-02     99.5633987623392     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     302041   37107129.7915863   7103.57103485782   -7103.57103485782   1.18541285913761    5.17446808792203E-02   -5.17446808792203E-02   0.1     125.597635644271     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
     CreateIbarraMaterial     301011   38341164.9744136   7394.53183970144   -7394.53183970144   1.18320409769455    5.02491065081866E-02   -5.02491065081866E-02   0.1     122.966728552845     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     301021   53149587.1683418   10687.0547141039   -10687.0547141039   1.1570177903656    3.56319978906433E-02   -3.56319978906433E-02   5.83703381471293E-02     95.4553464969131     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     301031   53149587.1683418   10687.0547141039   -10687.0547141039   1.1570177903656    3.56319978906433E-02   -3.56319978906433E-02   5.83703381471293E-02     95.4553464969131     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
     CreateIbarraMaterial     301041   38341164.9744136   7394.53183970144   -7394.53183970144   1.18320409769455    5.02491065081866E-02   -5.02491065081866E-02   0.1     122.966728552845     $c $resStrRatio $stiffFactor1 $stiffFactor2     180 
 
 
# Define the Beam Plastic Hinge Materials
#     The trailing 1 means a positively oriented material, while the trailing 2 is the same material flipped upside-down (for use on the left side of a joint element)
     #                               matTag EIeff mYPos mYNeg mcOverMy thetaCapPos thetaCapNeg thetaPC lambda c resStrRatio stiffFactor1 stiffFactor2 eleLength
     CreateIbarraMaterial     213011   71777178.9924472   1938.62665299092   -3975.84689880044   1.20998306893691    4.31711350168598E-02   -6.95471875571939E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     213012   71777178.9924472   3975.84689880044   -1938.62665299092   1.20998306893691    6.95471875571939E-02   -4.31711350168598E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     213021   71777178.9924472   1938.62665299092   -3975.84689880044   1.20998306893691    4.31711350168598E-02   -6.95471875571939E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     213022   71777178.9924472   3975.84689880044   -1938.62665299092   1.20998306893691    6.95471875571939E-02   -4.31711350168598E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     213031   71777178.9924472   1938.62665299092   -3975.84689880044   1.20998306893691    4.31711350168598E-02   -6.95471875571939E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     213032   71777178.9924472   3975.84689880044   -1938.62665299092   1.20998306893691    6.95471875571939E-02   -4.31711350168598E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     212011   71777178.9924472   2138.59112864692   -5427.50689953396   1.20998306893691    4.29881969509219E-02   -7.38527483121509E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     212012   71777178.9924472   5427.50689953396   -2138.59112864692   1.20998306893691    7.38527483121509E-02   -4.29881969509219E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     212021   71777178.9924472   2138.59112864692   -5427.50689953396   1.20998306893691    4.29881969509219E-02   -7.38527483121509E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     212022   71777178.9924472   5427.50689953396   -2138.59112864692   1.20998306893691    7.38527483121509E-02   -4.29881969509219E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     212031   71777178.9924472   2138.59112864692   -5427.50689953396   1.20998306893691    4.29881969509219E-02   -7.38527483121509E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     212032   71777178.9924472   5427.50689953396   -2138.59112864692   1.20998306893691    7.38527483121509E-02   -4.29881969509219E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     211011   71777178.9924472   2446.52028630801   -5907.81647356117   1.20998306893691    4.42411237522999E-02   -7.36882333227118E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     211012   71777178.9924472   5907.81647356117   -2446.52028630801   1.20998306893691    7.36882333227118E-02   -4.42411237522999E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     211021   71777178.9924472   2446.52028630801   -5907.81647356117   1.20998306893691    4.42411237522999E-02   -7.36882333227118E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     211022   71777178.9924472   5907.81647356117   -2446.52028630801   1.20998306893691    7.36882333227118E-02   -4.42411237522999E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     211031   71777178.9924472   2446.52028630801   -5907.81647356117   1.20998306893691    4.42411237522999E-02   -7.36882333227118E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     211032   71777178.9924472   5907.81647356117   -2446.52028630801   1.20998306893691    7.36882333227118E-02   -4.42411237522999E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     210011   71777178.9924472   2695.24389472707   -6386.24229181368   1.20998306893691    4.51378065351354E-02   -7.40226483697085E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     210012   71777178.9924472   6386.24229181368   -2695.24389472707   1.20998306893691    7.40226483697085E-02   -4.51378065351354E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     210021   71777178.9924472   2695.24389472707   -6386.24229181368   1.20998306893691    4.51378065351354E-02   -7.40226483697085E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     210022   71777178.9924472   6386.24229181368   -2695.24389472707   1.20998306893691    7.40226483697085E-02   -4.51378065351354E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     210031   71777178.9924472   2695.24389472707   -6386.24229181368   1.20998306893691    4.51378065351354E-02   -7.40226483697085E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     210032   71777178.9924472   6386.24229181368   -2695.24389472707   1.20998306893691    7.40226483697085E-02   -4.51378065351354E-02   0.1     175.591035119032     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     209011   147056601.303569   3317.56746644239   -8238.7360836896   1.20998306893691    3.42305771691732E-02   -5.76107958891479E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     209012   147056601.303569   8238.7360836896   -3317.56746644239   1.20998306893691    5.76107958891479E-02   -3.42305771691732E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     209021   147056601.303569   3317.56746644239   -8238.7360836896   1.20998306893691    3.42305771691732E-02   -5.76107958891479E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     209022   147056601.303569   8238.7360836896   -3317.56746644239   1.20998306893691    5.76107958891479E-02   -3.42305771691732E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     209031   147056601.303569   3317.56746644239   -8238.7360836896   1.20998306893691    3.42305771691732E-02   -5.76107958891479E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     209032   147056601.303569   8238.7360836896   -3317.56746644239   1.20998306893691    5.76107958891479E-02   -3.42305771691732E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     208011   147056601.303569   3317.56746644239   -8238.7360836896   1.20998306893691    3.42305771691732E-02   -5.76107958891479E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     208012   147056601.303569   8238.7360836896   -3317.56746644239   1.20998306893691    5.76107958891479E-02   -3.42305771691732E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     208021   147056601.303569   3317.56746644239   -8238.7360836896   1.20998306893691    3.42305771691732E-02   -5.76107958891479E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     208022   147056601.303569   8238.7360836896   -3317.56746644239   1.20998306893691    5.76107958891479E-02   -3.42305771691732E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     208031   147056601.303569   3317.56746644239   -8238.7360836896   1.20998306893691    3.42305771691732E-02   -5.76107958891479E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     208032   147056601.303569   8238.7360836896   -3317.56746644239   1.20998306893691    5.76107958891479E-02   -3.42305771691732E-02   9.63381102851702E-02     173.771060736736     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     207011   147056601.303569   3553.2305797568   -8448.64028585553   1.20998306893691    4.43425299354453E-02   -7.29881407938233E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     207012   147056601.303569   8448.64028585553   -3553.2305797568   1.20998306893691    7.29881407938233E-02   -4.43425299354453E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     207021   147056601.303569   3553.2305797568   -8448.64028585553   1.20998306893691    4.43425299354453E-02   -7.29881407938233E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     207022   147056601.303569   8448.64028585553   -3553.2305797568   1.20998306893691    7.29881407938233E-02   -4.43425299354453E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     207031   147056601.303569   3553.2305797568   -8448.64028585553   1.20998306893691    4.43425299354453E-02   -7.29881407938233E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     207032   147056601.303569   8448.64028585553   -3553.2305797568   1.20998306893691    7.29881407938233E-02   -4.43425299354453E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     206011   147056601.303569   3553.09709950626   -8655.60569665703   1.20998306893691    4.44081050517014E-02   -7.37730375547366E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     206012   147056601.303569   8655.60569665703   -3553.09709950626   1.20998306893691    7.37730375547366E-02   -4.44081050517014E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     206021   147056601.303569   3553.09709950626   -8655.60569665703   1.20998306893691    4.44081050517014E-02   -7.37730375547366E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     206022   147056601.303569   8655.60569665703   -3553.09709950626   1.20998306893691    7.37730375547366E-02   -4.44081050517014E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     206031   147056601.303569   3553.09709950626   -8655.60569665703   1.20998306893691    4.44081050517014E-02   -7.37730375547366E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     206032   147056601.303569   8655.60569665703   -3553.09709950626   1.20998306893691    7.37730375547366E-02   -4.44081050517014E-02   0.1     181.796406857179     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     205011   147056601.303569   3534.75428225975   -8725.38614966899   1.20998306893691    4.62897815404813E-02   -7.73198666251095E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205012   147056601.303569   8725.38614966899   -3534.75428225975   1.20998306893691    7.73198666251095E-02   -4.62897815404813E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205021   147056601.303569   3534.75428225975   -8725.38614966899   1.20998306893691    4.62897815404813E-02   -7.73198666251095E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205022   147056601.303569   8725.38614966899   -3534.75428225975   1.20998306893691    7.73198666251095E-02   -4.62897815404813E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205031   147056601.303569   3534.75428225975   -8725.38614966899   1.20998306893691    4.62897815404813E-02   -7.73198666251095E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     205032   147056601.303569   8725.38614966899   -3534.75428225975   1.20998306893691    7.73198666251095E-02   -4.62897815404813E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     204011   147056601.303569   3534.75428225975   -8725.38614966899   1.20998306893691    4.62897815404813E-02   -7.73198666251095E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204012   147056601.303569   8725.38614966899   -3534.75428225975   1.20998306893691    7.73198666251095E-02   -4.62897815404813E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204021   147056601.303569   3534.75428225975   -8725.38614966899   1.20998306893691    4.62897815404813E-02   -7.73198666251095E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204022   147056601.303569   8725.38614966899   -3534.75428225975   1.20998306893691    7.73198666251095E-02   -4.62897815404813E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204031   147056601.303569   3534.75428225975   -8725.38614966899   1.20998306893691    4.62897815404813E-02   -7.73198666251095E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     204032   147056601.303569   8725.38614966899   -3534.75428225975   1.20998306893691    7.73198666251095E-02   -4.62897815404813E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     203011   147056601.303569   3770.25835905933   -8521.30870022435   1.20998306893691    4.72065008639291E-02   -7.58445305585072E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203012   147056601.303569   8521.30870022435   -3770.25835905933   1.20998306893691    7.58445305585072E-02   -4.72065008639291E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203021   147056601.303569   3770.25835905933   -8521.30870022435   1.20998306893691    4.72065008639291E-02   -7.58445305585072E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203022   147056601.303569   8521.30870022435   -3770.25835905933   1.20998306893691    7.58445305585072E-02   -4.72065008639291E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203031   147056601.303569   3770.25835905933   -8521.30870022435   1.20998306893691    4.72065008639291E-02   -7.58445305585072E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     203032   147056601.303569   8521.30870022435   -3770.25835905933   1.20998306893691    7.58445305585072E-02   -4.72065008639291E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
     CreateIbarraMaterial     202011   147056601.303569   4284.02508089239   -8319.52914963406   1.20998306893691    4.91790423399924E-02   -7.37965427754594E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202012   147056601.303569   8319.52914963406   -4284.02508089239   1.20998306893691    7.37965427754594E-02   -4.91790423399924E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202021   147056601.303569   4284.02508089239   -8319.52914963406   1.20998306893691    4.91790423399924E-02   -7.37965427754594E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202022   147056601.303569   8319.52914963406   -4284.02508089239   1.20998306893691    7.37965427754594E-02   -4.91790423399924E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202031   147056601.303569   4284.02508089239   -8319.52914963406   1.20998306893691    4.91790423399924E-02   -7.37965427754594E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
     CreateIbarraMaterial     202032   147056601.303569   8319.52914963406   -4284.02508089239   1.20998306893691    7.37965427754594E-02   -4.91790423399924E-02   0.1     190.192391103901     $c $resStrRatio $stiffFactor1 $stiffFactor2     218 
 
 
# Define the Elastic Footing Rotational Stiffness Materials (this includes link beam and footing-soil stiffness
     uniaxialMaterial Elastic    601  3637885.33434446 
     uniaxialMaterial Elastic    602  3637885.33434446 
     uniaxialMaterial Elastic    603  3637885.33434446 
     uniaxialMaterial Elastic    604  3637885.33434446 
 
#########################################################################################################################
### DEFINE NODES
 
# Define the Elastic Footing Rotational Stiffness Materials (this includes link beam and footing-soil stiffness
      #   nodeNum   X   Y
     node   201011  0 0 
     node   201012  0 0 
     node   201013  0 0 
     node   201021  240 0 
     node   201022  240 0 
     node   201023  240 0 
     node   201031  480 0 
     node   201032  480 0 
     node   201033  480 0 
     node   201041  720 0 
     node   201042  720 0 
     node   201043  720 0 
 
# Define the nodes around all of the joints in the primary frame
      #   nodeNum   X   Y
     node   213011  0 1874 
     node   213012  11 1885 
     node   213013  0 1896 
     node   213014  -11 1885 
     node   213021  240 1874 
     node   213022  251 1885 
     node   213023  240 1896 
     node   213024  229 1885 
     node   213031  480 1874 
     node   213032  491 1885 
     node   213033  480 1896 
     node   213034  469 1885 
     node   213041  720 1874 
     node   213042  731 1885 
     node   213043  720 1896 
     node   213044  709 1885 
 
     node   212011  0 1718 
     node   212012  11 1729 
     node   212013  0 1740 
     node   212014  -11 1729 
     node   212021  240 1718 
     node   212022  251 1729 
     node   212023  240 1740 
     node   212024  229 1729 
     node   212031  480 1718 
     node   212032  491 1729 
     node   212033  480 1740 
     node   212034  469 1729 
     node   212041  720 1718 
     node   212042  731 1729 
     node   212043  720 1740 
     node   212044  709 1729 
 
     node   211011  0 1562 
     node   211012  11 1573 
     node   211013  0 1584 
     node   211014  -11 1573 
     node   211021  240 1562 
     node   211022  251 1573 
     node   211023  240 1584 
     node   211024  229 1573 
     node   211031  480 1562 
     node   211032  491 1573 
     node   211033  480 1584 
     node   211034  469 1573 
     node   211041  720 1562 
     node   211042  731 1573 
     node   211043  720 1584 
     node   211044  709 1573 
 
     node   210011  0 1406 
     node   210012  11 1417 
     node   210013  0 1428 
     node   210014  -11 1417 
     node   210021  240 1406 
     node   210022  251 1417 
     node   210023  240 1428 
     node   210024  229 1417 
     node   210031  480 1406 
     node   210032  491 1417 
     node   210033  480 1428 
     node   210034  469 1417 
     node   210041  720 1406 
     node   210042  731 1417 
     node   210043  720 1428 
     node   210044  709 1417 
 
     node   209011  0 1244 
     node   209012  11 1258 
     node   209013  0 1272 
     node   209014  -11 1258 
     node   209021  240 1244 
     node   209022  251 1258 
     node   209023  240 1272 
     node   209024  229 1258 
     node   209031  480 1244 
     node   209032  491 1258 
     node   209033  480 1272 
     node   209034  469 1258 
     node   209041  720 1244 
     node   209042  731 1258 
     node   209043  720 1272 
     node   209044  709 1258 
 
     node   208011  0 1088 
     node   208012  11 1102 
     node   208013  0 1116 
     node   208014  -11 1102 
     node   208021  240 1088 
     node   208022  251 1102 
     node   208023  240 1116 
     node   208024  229 1102 
     node   208031  480 1088 
     node   208032  491 1102 
     node   208033  480 1116 
     node   208034  469 1102 
     node   208041  720 1088 
     node   208042  731 1102 
     node   208043  720 1116 
     node   208044  709 1102 
 
     node   207011  0 932 
     node   207012  11 946 
     node   207013  0 960 
     node   207014  -11 946 
     node   207021  240 932 
     node   207022  251 946 
     node   207023  240 960 
     node   207024  229 946 
     node   207031  480 932 
     node   207032  491 946 
     node   207033  480 960 
     node   207034  469 946 
     node   207041  720 932 
     node   207042  731 946 
     node   207043  720 960 
     node   207044  709 946 
 
     node   206011  0 776 
     node   206012  11 790 
     node   206013  0 804 
     node   206014  -11 790 
     node   206021  240 776 
     node   206022  251 790 
     node   206023  240 804 
     node   206024  229 790 
     node   206031  480 776 
     node   206032  491 790 
     node   206033  480 804 
     node   206034  469 790 
     node   206041  720 776 
     node   206042  731 790 
     node   206043  720 804 
     node   206044  709 790 
 
     node   205011  0 620 
     node   205012  11 634 
     node   205013  0 648 
     node   205014  -11 634 
     node   205021  240 620 
     node   205022  251 634 
     node   205023  240 648 
     node   205024  229 634 
     node   205031  480 620 
     node   205032  491 634 
     node   205033  480 648 
     node   205034  469 634 
     node   205041  720 620 
     node   205042  731 634 
     node   205043  720 648 
     node   205044  709 634 
 
     node   204011  0 464 
     node   204012  11 478 
     node   204013  0 492 
     node   204014  -11 478 
     node   204021  240 464 
     node   204022  251 478 
     node   204023  240 492 
     node   204024  229 478 
     node   204031  480 464 
     node   204032  491 478 
     node   204033  480 492 
     node   204034  469 478 
     node   204041  720 464 
     node   204042  731 478 
     node   204043  720 492 
     node   204044  709 478 
 
     node   203011  0 308 
     node   203012  11 322 
     node   203013  0 336 
     node   203014  -11 322 
     node   203021  240 308 
     node   203022  251 322 
     node   203023  240 336 
     node   203024  229 322 
     node   203031  480 308 
     node   203032  491 322 
     node   203033  480 336 
     node   203034  469 322 
     node   203041  720 308 
     node   203042  731 322 
     node   203043  720 336 
     node   203044  709 322 
 
     node   202011  0 152 
     node   202012  11 166 
     node   202013  0 180 
     node   202014  -11 166 
     node   202021  240 152 
     node   202022  251 166 
     node   202023  240 180 
     node   202024  229 166 
     node   202031  480 152 
     node   202032  491 166 
     node   202033  480 180 
     node   202034  469 166 
     node   202041  720 152 
     node   202042  731 166 
     node   202043  720 180 
     node   202044  709 166 
 
# Define the nodes around all of the joints in the primary frame
node 3131 840 1896
node 3121 840 1740
node 3123 840 1740
equalDOF 3123 3121 1 2
node 3111 840 1584
node 3113 840 1584
equalDOF 3113 3111 1 2
node 3101 840 1428
node 3103 840 1428
equalDOF 3103 3101 1 2
node 3091 840 1272
node 3093 840 1272
equalDOF 3093 3091 1 2
node 3081 840 1116
node 3083 840 1116
equalDOF 3083 3081 1 2
node 3071 840 960
node 3073 840 960
equalDOF 3073 3071 1 2
node 3061 840 804
node 3063 840 804
equalDOF 3063 3061 1 2
node 3051 840 648
node 3053 840 648
equalDOF 3053 3051 1 2
node 3041 840 492
node 3043 840 492
equalDOF 3043 3041 1 2
node 3031 840 336
node 3033 840 336
equalDOF 3033 3031 1 2
node 3021 840 180
node 3023 840 180
equalDOF 3023 3021 1 2
node 3013 840 0
 
#########################################################################################################################
### DEFINE FIXITIES
 
# Define the fixities at the bases of the columns of the primary lateral frame
#       node    DX DY RZ
     fix    201011    1  1  1 
     fix    201021    1  1  1 
     fix    201031    1  1  1 
     fix    201041    1  1  1 
 
# Define the fixity at the baseof the leaning column
#       node    DX DY RZ
fix 3013 1 1 0
 
#########################################################################################################################
### DEFINE ELEMENTS
 
# Define the column elements
             ##                 tag     node1   node2       EA      EofUnity    EI          geomTransf  
     element elasticBeamColumn   31201 212013 213011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   31202 212023 213021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   31203 212033 213031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   31204 212043 213041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   31101 211013 212011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   31102 211023 212021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   31103 211033 212031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   31104 211043 212041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   31001 210013 211011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   31002 210023 211021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   31003 210033 211031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   31004 210043 211041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30901 209013 210011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30902 209023 210021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30903 209033 210031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30904 209043 210041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30801 208013 209011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30802 208023 209021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30803 208033 209031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30804 208043 209041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30701 207013 208011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30702 207023 208021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30703 207033 208031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30704 207043 208041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30601 206013 207011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30602 206023 207021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30603 206033 207031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30604 206043 207041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30501 205013 206011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30502 205023 206021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30503 205033 206031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30504 205043 206041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30401 204013 205011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30402 204023 205021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30403 204033 205031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30404 204043 205041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30301 203013 204011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30302 203023 204021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30303 203033 204031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30304 203043 204041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30201 202013 203011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30202 202023 203021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30203 202033 203031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30204 202043 203041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
     element elasticBeamColumn   30101 201013 202011   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
     element elasticBeamColumn   30102 201023 202021   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30103 201033 202031   $EAcol  $EOfUnity   53149587.1683418  $primaryGeomTransT 
     element elasticBeamColumn   30104 201043 202041   $EAcol  $EOfUnity   38341164.9744136  $primaryGeomTransT 
 
# Define the beam elements
             ##                 tag     node1   node2       EA      EofUnity    EI          geomTransf  
     element elasticBeamColumn   21301 213012 213024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21302 213022 213034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21303 213032 213044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   21201 212012 212024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21202 212022 212034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21203 212032 212044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   21101 211012 211024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21102 211022 211034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21103 211032 211044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   21001 210012 210024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21002 210022 210034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   21003 210032 210044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20901 209012 209024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20902 209022 209034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20903 209032 209044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20801 208012 208024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20802 208022 208034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20803 208032 208044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20701 207012 207024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20702 207022 207034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20703 207032 207044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20601 206012 206024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20602 206022 206034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20603 206032 206044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20501 205012 205024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20502 205022 205034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20503 205032 205044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20401 204012 204024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20402 204022 204034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20403 204032 204044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20301 203012 203024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20302 203022 203034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20303 203032 203044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
     element elasticBeamColumn   20201 202012 202024   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20202 202022 202034   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
     element elasticBeamColumn   20203 202032 202044   $EABm  $EOfUnity   147056601.303569  $primaryGeomTransT 
 
 
# Define the column base rotational spring (both elastic foundation springs and column base PH springs)
     ##  eleID nodeR nodeC matID 
     rotSpring2D     6011    201011  201012  601 
     rotSpring2D     6012    201012  201013  301011 
 
     rotSpring2D     6021    201021  201022  602 
     rotSpring2D     6022    201022  201023  301021 
 
     rotSpring2D     6031    201031  201032  603 
     rotSpring2D     6032    201032  201033  301031 
 
     rotSpring2D     6041    201041  201042  604 
     rotSpring2D     6042    201042  201043  301041 
 
# Define the joint elements
    #                  tag         n1       n2     n3     n4       centerNode  PH1     PH2     PH3     PH4     shearPanel  largeDisp
     element Joint2D     41301       213011  213012  213013  213014  213015      312011   213011   49999  49999  41301       $lrgDsp 
     element Joint2D     41302       213021  213022  213023  213024  213025      312021   213021   49999  213012  41302       $lrgDsp 
     element Joint2D     41303       213031  213032  213033  213034  213035      312031   213031   49999  213022  41303       $lrgDsp 
     element Joint2D     41304       213041  213042  213043  213044  213045      312041   49999   49999  213032  41304       $lrgDsp 
 
     element Joint2D     41201       212011  212012  212013  212014  212015      311011   212011   312011  49999  41201       $lrgDsp 
     element Joint2D     41202       212021  212022  212023  212024  212025      311021   212021   312021  212012  41202       $lrgDsp 
     element Joint2D     41203       212031  212032  212033  212034  212035      311031   212031   312031  212022  41203       $lrgDsp 
     element Joint2D     41204       212041  212042  212043  212044  212045      311041   49999   312041  212032  41204       $lrgDsp 
 
     element Joint2D     41101       211011  211012  211013  211014  211015      310011   211011   311011  49999  41101       $lrgDsp 
     element Joint2D     41102       211021  211022  211023  211024  211025      310021   211021   311021  211012  41102       $lrgDsp 
     element Joint2D     41103       211031  211032  211033  211034  211035      310031   211031   311031  211022  41103       $lrgDsp 
     element Joint2D     41104       211041  211042  211043  211044  211045      310041   49999   311041  211032  41104       $lrgDsp 
 
     element Joint2D     41001       210011  210012  210013  210014  210015      309011   210011   310011  49999  41001       $lrgDsp 
     element Joint2D     41002       210021  210022  210023  210024  210025      309021   210021   310021  210012  41002       $lrgDsp 
     element Joint2D     41003       210031  210032  210033  210034  210035      309031   210031   310031  210022  41003       $lrgDsp 
     element Joint2D     41004       210041  210042  210043  210044  210045      309041   49999   310041  210032  41004       $lrgDsp 
 
     element Joint2D     40901       209011  209012  209013  209014  209015      308011   209011   309011  49999  40901       $lrgDsp 
     element Joint2D     40902       209021  209022  209023  209024  209025      308021   209021   309021  209012  40902       $lrgDsp 
     element Joint2D     40903       209031  209032  209033  209034  209035      308031   209031   309031  209022  40903       $lrgDsp 
     element Joint2D     40904       209041  209042  209043  209044  209045      308041   49999   309041  209032  40904       $lrgDsp 
 
     element Joint2D     40801       208011  208012  208013  208014  208015      307011   208011   308011  49999  40801       $lrgDsp 
     element Joint2D     40802       208021  208022  208023  208024  208025      307021   208021   308021  208012  40802       $lrgDsp 
     element Joint2D     40803       208031  208032  208033  208034  208035      307031   208031   308031  208022  40803       $lrgDsp 
     element Joint2D     40804       208041  208042  208043  208044  208045      307041   49999   308041  208032  40804       $lrgDsp 
 
     element Joint2D     40701       207011  207012  207013  207014  207015      306011   207011   307011  49999  40701       $lrgDsp 
     element Joint2D     40702       207021  207022  207023  207024  207025      306021   207021   307021  207012  40702       $lrgDsp 
     element Joint2D     40703       207031  207032  207033  207034  207035      306031   207031   307031  207022  40703       $lrgDsp 
     element Joint2D     40704       207041  207042  207043  207044  207045      306041   49999   307041  207032  40704       $lrgDsp 
 
     element Joint2D     40601       206011  206012  206013  206014  206015      305011   206011   306011  49999  40601       $lrgDsp 
     element Joint2D     40602       206021  206022  206023  206024  206025      305021   206021   306021  206012  40602       $lrgDsp 
     element Joint2D     40603       206031  206032  206033  206034  206035      305031   206031   306031  206022  40603       $lrgDsp 
     element Joint2D     40604       206041  206042  206043  206044  206045      305041   49999   306041  206032  40604       $lrgDsp 
 
     element Joint2D     40501       205011  205012  205013  205014  205015      304011   205011   305011  49999  40501       $lrgDsp 
     element Joint2D     40502       205021  205022  205023  205024  205025      304021   205021   305021  205012  40502       $lrgDsp 
     element Joint2D     40503       205031  205032  205033  205034  205035      304031   205031   305031  205022  40503       $lrgDsp 
     element Joint2D     40504       205041  205042  205043  205044  205045      304041   49999   305041  205032  40504       $lrgDsp 
 
     element Joint2D     40401       204011  204012  204013  204014  204015      303011   204011   304011  49999  40401       $lrgDsp 
     element Joint2D     40402       204021  204022  204023  204024  204025      303021   204021   304021  204012  40402       $lrgDsp 
     element Joint2D     40403       204031  204032  204033  204034  204035      303031   204031   304031  204022  40403       $lrgDsp 
     element Joint2D     40404       204041  204042  204043  204044  204045      303041   49999   304041  204032  40404       $lrgDsp 
 
     element Joint2D     40301       203011  203012  203013  203014  203015      302011   203011   303011  49999  40301       $lrgDsp 
     element Joint2D     40302       203021  203022  203023  203024  203025      302021   203021   303021  203012  40302       $lrgDsp 
     element Joint2D     40303       203031  203032  203033  203034  203035      302031   203031   303031  203022  40303       $lrgDsp 
     element Joint2D     40304       203041  203042  203043  203044  203045      302041   49999   303041  203032  40304       $lrgDsp 
 
     element Joint2D     40201       202011  202012  202013  202014  202015      301011   202011   302011  49999  40201       $lrgDsp 
     element Joint2D     40202       202021  202022  202023  202024  202025      301021   202021   302021  202012  40202       $lrgDsp 
     element Joint2D     40203       202031  202032  202033  202034  202035      301031   202031   302031  202022  40203       $lrgDsp 
     element Joint2D     40204       202041  202042  202043  202044  202045      301041   49999   302041  202032  40204       $lrgDsp 
 
# Define the leaning column and horizintal rigid link elements
element elasticBeamColumn 5121 3123 3131 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5111 3113 3121 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5101 3103 3111 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5091 3093 3101 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5081 3083 3091 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5071 3073 3081 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5061 3063 3071 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5051 3053 3061 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5041 3043 3051 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5031 3033 3041 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5021 3023 3031 $Acol $E_strut $I_strut $primaryGeomTransT
element elasticBeamColumn 5011 3013 3021 $Acol $E_strut $I_strut $primaryGeomTransT
 
element truss 5132 213043 3131 $A_strut $strutMatT
element truss 5122 212043 3121 $A_strut $strutMatT
element truss 5112 211043 3111 $A_strut $strutMatT
element truss 5102 210043 3101 $A_strut $strutMatT
element truss 5092 209043 3091 $A_strut $strutMatT
element truss 5082 208043 3081 $A_strut $strutMatT
element truss 5072 207043 3071 $A_strut $strutMatT
element truss 5062 206043 3061 $A_strut $strutMatT
element truss 5052 205043 3051 $A_strut $strutMatT
element truss 5042 204043 3041 $A_strut $strutMatT
element truss 5032 203043 3031 $A_strut $strutMatT
element truss 5022 202043 3021 $A_strut $strutMatT
 
#########################################################################################################################
### DEFINE GRAVITY LOADS
 
      pattern Plain 1 Linear {
             # Distributed beam element loads
             eleLoad -ele  21301 21302 21303 21201 21202 21203 21101 21102 21103 21001 21002 21003 20901 20902 20903 20801 20802 20803 20701 20702 20703 20601 20602 20603 20501 20502 20503 20401 20402 20403 20301 20302 20303 20201 20202 20203   -type -beamUniform   -0.32275
             # Point gravity loads on leaning column
             #        node    X   Y           M
load 3131 0.0 -28.402 0.0
load 3123 0.0 -28.402 0.0
load 3113 0.0 -28.402 0.0
load 3103 0.0 -28.402 0.0
load 3093 0.0 -28.402 0.0
load 3083 0.0 -28.402 0.0
load 3073 0.0 -28.402 0.0
load 3063 0.0 -28.402 0.0
load 3053 0.0 -28.402 0.0
load 3043 0.0 -28.402 0.0
load 3033 0.0 -28.402 0.0
load 3023 0.0 -28.402 0.0
      }
 
#########################################################################################################################
### DEFINE MASSES
 
# Define small masses at all nodes as the column-foundation connection
      #       nodeNum    X    Y     Rotation
     mass   201011    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201012    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201013    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201021    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201022    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201023    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201031    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201032    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201033    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201041    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201042    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
     mass   201043    [expr $smallMass1]   [expr $smallMass2]   [expr $smallMass3]  
 
# Define small masses as the nodes around all of the joints in the primary frame
mass 3131 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3121 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3123 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3111 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3113 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3101 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3103 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3091 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3093 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3081 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3083 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3071 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3073 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3061 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3063 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3051 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3053 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3041 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3043 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3031 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3033 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3021 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3023 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
mass 3013 [expr $smallMass1] [expr $smallMass2] [expr $smallMass3]
 
# Define building masses
      #       nodeNum    X    Y     Rotation
     mass    213011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    213044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    212011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    212044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    211011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    211044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    210011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    210044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    209011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    209044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    208011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    208044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    207011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    207044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    206011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    206044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    205011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    205044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    204011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    204044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    203011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    203044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
     mass    202011       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202012       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202013       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202014       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202021       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202022       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202023       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202024       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202031       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202032       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202033       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202034       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202041       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202042       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202043       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
     mass    202044       3.73553240740741E-02     3.73553240740741E-02     [expr $smallMass3]
 
 # Check: Total mass applied to building is: 7.17222222222222.  This was summed in the VB loop when mass was applied. This does not include small masses applied for convergence. 
 
 #########################################################################################################################

### DEFINE ADDITIONAL INFORMATION
# Define the number of stories in the frame
set num_stories 12

# Define the control nodes used to compute story drifts
set ctrl_nodes {
    201023
    202023
    203023
    204023
    205023
    206023
    207023
    208023
    209023
    210023
    211023
    212023
    213023
}

#########################################################################################################################
### APPLY GRAVITY LOAD ###
#########################################################################################################################

# Recorders for gravity
 file mkdir $Output_path/gravity_drift
 file mkdir $Output_path/gravity_disp
 
# --Define the story drift recorders--
for {set story 1} {$story <= $num_stories} {incr story} {
   recorder Drift -file $Output_path/gravity_drift/gr_drift_story${story}.out -time -iNode [lindex $ctrl_nodes \
            [expr {$story - 1}]] -jNode [lindex $ctrl_nodes $story] -dof 1 -perpDirn 2
}

# Displacement
for {set story 1} {$story <= $num_stories} {incr story} {
    recorder Node -file $Output_path/gravity_disp/gr_disp_story${story}.out -time -node [lindex $ctrl_nodes $story] -dof 1 disp
}

set numsteps_grav 10
set tol 1e-12
set maxiter 20

constraints Transformation
numberer RCM
system SparseGEN
test RelativeEnergyIncr $tol $maxiter
algorithm Newton
integrator LoadControl [expr {1.0/$numsteps_grav}]
analysis Static

if {[analyze $numsteps_grav]} {puts "Application of gravity load failed"}

loadConst -time 0.0
wipeAnalysis
remove recorders

### DEFINE DAMPING OBJECTS
set eigenvalues [eigen -fullGenLapack [lindex $modes 1]]
set periodForRayleighDamping_1 [expr {2.0*$pi/sqrt([lindex $eigenvalues [lindex $modes 0]-1])}]
set periodForRayleighDamping_2 [expr {2.0*$pi/sqrt([lindex $eigenvalues [lindex $modes 1]-1])}]
 
# Define damping for all beams and all columns (i.e. elastic elements), but not on the joints b/c they have the nonlinearity in them.  This is the approach proposed by Medina.  Compute the damping paramters based on Chopra text page 457.
      set omegaI [expr (2.0 * $pi) / $periodForRayleighDamping_1]
      set omegaJ [expr (2.0 * $pi) / ($periodForRayleighDamping_2)]
      set alpha1Coeff [expr (2.0 * $omegaI * $omegaJ) / ($omegaI + $omegaJ)]
      set alpha2Coeff [expr (2.0) / ($omegaI + $omegaJ)]
      set alpha1  [expr $alpha1Coeff * $dampRat * $dampRatF]
      set alpha2  [expr $alpha2Coeff * $dampRat * $dampRatF]
      set alpha2ToUse [expr 1.1 * $alpha2];   # 1.1 factor is becuase we apply to only LE elements
      region 1 -eleRange  20201   31204   -rayleigh $alpha1 0 $alpha2ToUse 0;    # Initial stiffness"
 #--------------------------------------------------------------------------------------------------------------------------------------------------------

